name: Manage deployment on PR close

on:
  pull_request:
    types: [closed]
    branches:
      - master

env:
  RENDER_NAME_MASTER: "charity-portal-master"

jobs:
  getPrNumber:
    name: Get PR number
    env:
      PULL_NUMBER: ""
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
            const core = require('@actions/core');
            const prNumber = context.payload.number;
            core.exportVariable('PULL_NUMBER', prNumber);
      - name: Output PR number
        run: echo $PULL_NUMBER
      - name: Output host
        run: echo "https://${RENDER_NAME_MASTER}-pr-${PULL_NUMBER}.onrender.com"
