name: Manage deployment on open PR

on:
  pull_request:
    types: [opened]
    branches:
      - master

env:
  RENDER_NAME_MASTER: "charity-portal-master"

jobs:
  getPrNumber:
    name: Get PR number
    outputs:
      prNumber: ${{steps.prNumber.outputs.prNumber}}
    env:
      PULL_NUMBER: ""
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
            const core = require('@actions/core')
            const prNumber = context.payload.number;
            core.exportVariable('PULL_NUMBER', prNumber);
      - id: prNumber
        name: Output PR number
        run: echo "::set-output name=prNumber::${PULL_NUMBER}"
  addOrigin:
    needs: getPrNumber
    name: Add origin to Auth0
    runs-on: ubuntu-latest
    steps:
      - name: Output PR number again
        run: |
          echo ${{needs.getPrNumber.outputs.prNumber}}
      - name: Output host
        run: |
          echo "https://${RENDER_NAME_MASTER}-pr-${{needs.getPrNumber.outputs.pull_number}}.onrender.com"
        
