name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
            const core = require('@actions/core')
            const prNumber = context.payload.number;
            core.exportVariable('PULL_NUMBER', prNumber);
      - name: Output PR number
        run: |
          echo $PULL_NUMBER
      - uses: actions/checkout@v2
      - uses: azure/login@v1.1
        with:
          creds: ${{ secrets.Master_Credentials }}
      - name: Add render.com preview host to Auth0 origin
        run: |
          RENDER_NAME_MASTER="charity-portal-master"
          sh ./deploy_scripts/manage_auth0_origin.sh add "https://${RENDER_NAME_MASTER}-pr-${PULL_NUMBER}.onrender.com"
      - name: Remove render.com preview host from Auth0 origin
        run: |
          RENDER_NAME_MASTER="charity-portal-master"
          sh ./deploy_scripts/manage_auth0_origin.sh remove "https://${RENDER_NAME_MASTER}-pr-${PULL_NUMBER}.onrender.com"
        
