name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{github.token}}
          script: |
            const core = require('@actions/core')
            const prNumber = context.payload.number;
            core.exportVariable('PULL_NUMBER', prNumber);
      - name: Output PR number
        run: |
          echo $PULL_NUMBER
      - uses: actions/checkout@v2
      - name: Build render domain
        with: |
          ls -la
          sh ./deploy_scripts/test.sh
        
